### ISSUE TITLE
GraphQLSevlet issue

### ISSUE THREAD

**Issue by killersite** [Cox-Automotive/graphql-java-tools#2]
Hi Andrew,
The readonly properties of the GraphQLServlet is causing errors for me in your example. Do you have a way around this? thanks

Here
```
@PostConstruct
    void postConstruct() {
        this.readOnlySchema = graphQLSchema
        this.schema = graphQLSchema
    }
```

Caused by: groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: readOnlySchema for class: com.hbo.example.servlet.GraphQLController

**Comment by apottere** [comment]
AFAICT those fields aren't read-only in the [latest release](https://mvnrepository.com/artifact/com.graphql-java/graphql-java-servlet/0.9.0) nor on [current master](https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLServlet.java#L71).  What version of graphql-java-servlet are you bringing in?  They should be package-private but not final.

**Comment by apottere** [comment]
I'm not actually familiar with when `ReadOnlyPropertyException` is thrown, but it's possible it's because your controller class is in `com.hbo.example.servlet` instead of `graphql.servlet`.  I have an open pull request with graphql-java-servlet to allow setting those fields directly, but for now (since the fields are package-private), your controller class has to be in the same package as the servlet.

**Comment by killersite** [comment]
Maybe this is a Groovy thing accessing the graphql.servlet package class...
thanks

**Comment by killersite** [comment]
works fine in a java only project but if I mix in any groovy things seem to get locked down hard.

**Comment by apottere** [comment]
Interesting, I can take a look at putting groovy in the example.

**Comment by apottere** [comment]
This is the relevant PR: https://github.com/graphql-java/graphql-java-servlet/pull/15.  Ideally you wouldn't have to worry about package-private fields.

**Comment by killersite** [comment]
So this looks to be caused by the inclusion of Spring DevTools in the mix and nothing to do with Groovy. Thanks.

**Comment by apottere** [comment]
Oh, cool.  I'll see if I can get it working with spring-devtools anyway.
