### ISSUE TITLE
Mutations???

### ISSUE THREAD

**Issue by oexza** [Cox-Automotive/graphql-java-tools#3]
How are mutations to be defined?

**Comment by oexza** [comment]
i tried 
`public class Mutation extends GraphQLRootResolver{
    //...... 
}` no luck

**Comment by hloydl** [comment]
Mutations do works - take a look here: 
https://github.com/Loydl/camunda-graphql/blob/master/src/main/java/graphql/resolvers/Mutation.java

**Comment by oexza** [comment]
Ahh my bad! turns out that my Schema definition had a typo. thanks
