### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by hloydl** [Cox-Automotive/graphql-java-tools#4]
Hi guys, good work. 

We would like to base our project [camunda-graphql ](https://github.com/Loydl/camunda-graphql)on your graphql-java-tools. 
My question: 
When using graphq-java-tools what is the best way or level to implement [GraphQL Error Handling](http://facebook.github.io/graphql/#sec-Errors)?
I.e. error/exception handling when something goes wrong in the resolvers, like [here](https://github.com/Loydl/camunda-graphql/blob/master/src/main/java/graphql/resolvers/Mutation.java#L40) for example.
Currently the error gets reported on the server console, but the response in GraphiQL look like this: 
![image](https://cloud.githubusercontent.com/assets/7716757/23854062/ec1b5bd0-07ef-11e7-81f5-ee625036f976.png)

How can I put the exception-message ("no processes deployed with key 'x': processDefinition is null") from the API-call into the GraphQL response?  

**Update**: it looks like [GraphQLServlet](https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLServlet.java#L313) is responsible for adding the error(s) to the response. Although there are errors (here: ExceptionWhileDataFetching) from the result of `new GraphQL`  (which is OK) they are not getting inserted into the JSON-response.

**Comment by apottere** [comment]
Yeah, I suspected it was something in the servlet that was squelching the errors.  When that project becomes active again I'll work with the author to provide an option to pass those errors to the client as well.

**Comment by hloydl** [comment]
So, what can we do if the project [GraphQLServlet](https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLServlet.java) never gets active again?
Can we fork it and continue to maintain it using another name? 
How is that problem of dependent and inactive projects solved in the Java open source community? 

BTW, further analysis of [GraphQLServlet](https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLServlet.java#L313) shows that only these two error types - InvalidSyntaxError and ValidationError - are supported in the GraphQL JSON response. Because of this [line](https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLServlet.java#L326). If you omit the filter, you get all errors.

**Comment by apottere** [comment]
I was planning on forking and publishing a version of the servlet soon if it stays inactive.

**Comment by hloydl** [comment]
You have my support.

**Comment by apottere** [comment]
@hloydl this should be doable as of `graphql-java-servlet:1.0.0`.  Simply subclass the servlet and override the method that filters errors out.

**Comment by apottere** [comment]
If you want a more robust solution definitely create an issue in that project with a description of how you'd like it to work.
